sudo: required
services:
  - docker
dist: trusty
language: python
python:
  - "3.6"
notifications:
  email: false

install:
   # need aws to pull smarthp-hardwaresim docker image
   - pip install --upgrade pip==20.2.3
   - pip install awscli flake8==3.5.0 pyyaml pytest
   - export PATH=$PATH:$HOME/.local/bin # put aws in the path
   - eval $(aws ecr get-login --region us-east-2 --no-include-email)

script:
  - docker build -f Dockerfile.server -t 407636574581.dkr.ecr.us-east-2.amazonaws.com/xviz:latest .      
  - docker push 407636574581.dkr.ecr.us-east-2.amazonaws.com/xviz:latest