sudo: required

language:
  python

python:
  - "3.6"

# we'll handle submodules ourselves
git:
  submodules: false

env:
  - CI=true

services:
  - docker

install: 
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker --version
  - pip install awscli
  - cp .netrc ~/.netrc
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - git submodule update --init --recursive || travis_terminate 1
  - eval $(aws ecr get-login --region us-east-2 --no-include-email)
  - cd html
  - npm install
  - cd ..

before_script:
  - export NODE_OPTIONS=--max_old_space_size=4096
  - /bin/bash release_management.sh check_release_version mc_ui 2 3 4 || travis_terminate 1

script:
  # run the ui tests
  - cd html
  - npm run lint || travis_terminate 1
  - npm run test || travis_terminate 1
  - npm run test:coverage || travis_terminate 1
  - cd ..
  - ./deploy.sh
  # run the tests
  # - docker-compose up --exit-code-from mc-ui || travis_terminate 1;
  - docker build -f Dockerfile.server -t 407636574581.dkr.ecr.us-east-2.amazonaws.com/xviz:latest .      
  - docker push 407636574581.dkr.ecr.us-east-2.amazonaws.com/xviz:latest