collector_output_file: /home/r103867/work/camera-collector/nd-data/stops_without_state/radar_stop_headdown_without_state.tar
extract_directory: /home/r103867/work/camera-collector/nd-data/stop_2/txt_files

radar_filter:
  qfilter_enabled: True
  queue_size: 12
  consecutive_min: 7
  pexist_min: 0.8
  d_bpower_min: -10
  phi_sdv_max: 0.1
  nan_threshold: 0.5