collector_output_file: /Users/azizalibasic/Downloads/v2020-25-0-6de872fc781a4edba9139698ec01f5d8-detection-primary-forward-57-smartag-autocart-1596653720420-792.tar
extract_directory: /Users/azizalibasic/Documents/dev/VIZ_STACK/xviz/python/examples/scenarios/tmp/

radar_filter:
  qfilter_enabled: True
  queue_size: 12
  consecutive_min: 7
  pexist_min: 0.8
  d_bpower_min: -10
  phi_sdv_max: 0.1
  nan_threshold: 0.5