collector_output_file: /home/raven.ravenind.net/r103943/Desktop/collector/today/v2020-3-0-01474c5e94b248948cc32b0081d21b22-detection-primary-forward-57-smartag-autocart-1597359788663-143.tar
extract_directory: /home/raven.ravenind.net/r103943/Desktop/collector/extracted
