collector_output_file: /Users/azizalibasic/Desktop/important/california-duplicate-points/failure_after_change/Estop_pressed-v2020-25-0-83dcccfd63c54194b59d9c295f103a10-smartag-autocart-1617805231238-696.tar
extract_directory: /Users/azizalibasic/Downloads/temp/
mqtt_enabled: False
IVT: True
MACHINE_TYPE: 8RIVT_WHEEL
