collector_output_file: /Users/azizalibasic/Desktop/2020_ND_Aziz/data_collection/day3/running_sync_day3/day3_running/v2020-3-0-01474c5e94b248948cc32b0081d21b22-detection-primary-forward-57-smartag-autocart-1597360737774-516.tar
extract_directory: /Users/azizalibasic/Desktop/2020_ND_Aziz/data_collection/day3/running_sync_day3/day3_running/extracted6

radar_filter:
  qfilter_enabled: True
  queue_size: 12
  consecutive_min: 7
  pexist_min: 0.8
  d_bpower_min: -10
  phi_sdv_max: 0.1
  nan_threshold: 0.5