collector_output_file: /home/raven.ravenind.net/r103943/Desktop/collector/v2020-25-0-01474c5e94b248948cc32b0081d21b22-detection-primary-forward-57-smartag-autocart-1596642289318-188.tar
extract_directory: /home/raven.ravenind.net/r103943/Desktop/collector/extracted

radar_filter:
  qfilter_enabled: True
  queue_size: 12
  consecutive_min: 7
  pexist_min: 0.8
  d_bpower_min: -10
  phi_sdv_max: 0.1
  nan_threshold: 0.5